/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          light: '#7a5741',
          DEFAULT: '#5b3a26',
          dark: '#4e3323',
        },
        "surface-champagne": "#F9F6F0",
        "on-tertiary-fixed-variant": "#005137",
        "on-tertiary-container": "#f5fff7",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#613f2b",
        "surface-container": "#efecf5",
        "on-background": "#1b1b21",
        "background": "#fbf8ff",
        "tertiary": "#006948",
        "primary-container": "#b15f00",
        "primary-fixed": "#ffdcc3",
        "outline-variant": "#dbc2b0",
        "surface-dim": "#dbd9e1",
        "surface-variant": "#e4e1ea",
        "border-warm": "#E8DFD1",
        "inverse-on-surface": "#f2eff8",
        "secondary": "#7b5640",
        "surface-container-highest": "#e4e1ea",
        "surface-container-high": "#eae7ef",
        "primary-fixed-dim": "#ffb77d",
        "text-muted": "#6B7280",
        "on-tertiary": "#ffffff",
        "primary": "#8d4b00",
        "on-tertiary-fixed": "#002114",
        "status-verified": "#059669",
        "surface-card-subtle": "#F3EDE2",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#2e1505",
        "surface-container-low": "#f5f2fb",
        "outline": "#887364",
        "surface-bright": "#fbf8ff",
        "charcoal-dark": "#111827",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb77d",
        "tertiary-fixed": "#85f8c4",
        "tertiary-fixed-dim": "#68dba9",
        "amber-bright": "#F59E0B",
        "secondary-container": "#ffcdb1",
        "border-amber-light": "#FDE68A",
        "secondary-fixed-dim": "#edbca1",
        "on-secondary-container": "#7a553f",
        "surface-cream": "#FFFDF9",
        "on-primary-container": "#fffbff",
        "badge-popular-bg": "#1E1E24",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#6e3900",
        "on-primary": "#ffffff",
        "surface": "#fbf8ff",
        "on-surface-variant": "#554336",
        "badge-popular-fg": "#F59E0B",
        "on-primary-fixed": "#2f1500",
        "error": "#ba1a1a",
        "surface-tint": "#904d00",
        "tertiary-container": "#00855d",
        "on-surface": "#1b1b21",
        "secondary-fixed": "#ffdbc9",
        "inverse-surface": "#303036"
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
        "margin-desktop": "2.5rem",
        "margin": "1.25rem",
        "space-2xs": "0.125rem",
        "space-md": "1rem",
        "space-2xl": "3rem",
        "space-sm": "0.5rem",
        "gutter-sm": "0.75rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1rem"
      },
      fontFamily: {
        epilogue: ["Epilogue", "sans-serif"],
        jakarta: ["Plus Jakarta Sans", "sans-serif"],
      }
    },
  },
  plugins: [],
}